project_name: lanes
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - id: lanes
    main: ./cmd/lanes
    binary: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    no_unique_dist_dir: true
    ldflags:
      - -s
      - -X "github.com/codekoala/go-aws-lanes/version.Commit={{ .Tag }}"
      - -X "github.com/codekoala/go-aws-lanes/version.BuildDate={{ .Date }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    # hooks:
    #   post:
    #     - upx {{ .Path }}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
